.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "PODSEC\-MONITOR\-POLICY\-AND\-IMAGES" "1" "February 2024" ""
.SH "NAME"
\fBpodsec\-monitor\-policy\-and\-images\fR \-
.SH "SYNOPSIS"
\fBpodsec\-monitor\-policy\-and\-images\fR
.SH "DESCRIPTION"
.SH "OPTIONS"
.SH "EXAMPLES"
`podsec\-monitor\-policy\-and\-images
.SH "SECURITY CONSIDERATIONS"
.SH "SEE ALSO"
.SH "AUTHOR"
Костарев Алексей, Базальт СПО kaf@basealt\.ru
