.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "PODSEC\-INOTIFY\-CHECK\-POLICY" "1" "October 2024" ""
.SH "NAME"
\fBpodsec\-inotify\-check\-policy\fR \- The plugin checks the containerization policy settings on the node
.SH "SYNOPSIS"
\fBpodsec\-inotify\-check\-policy [\-v[vv]] [\-a interval] [\-f interval] \-c interval \-h interval [\-m interval] \-w intervalъ [\-l interval] [\-d interval] [\-M EMail]\fR
.SH "DESCRIPTION"
.SS "General description"
The plugin checks the containerization policy settings on the node\.
.P
The check is based on the following parameters:
.TP
file \fBpolicy\.json\fR settings of transports and access policies to registrars:

.IP "" 4
.nf
User Control Parameter | Metric Weight
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-|\-\-\-\-\-\-\-\-\-\-\-\-\-
having `defaultPolicy != reject`, but not included in the `podman_dev` group                                                 | 102
not having `registry\.local` in the list of registrars for which the presence of an electronic signature of images is checked | 103
having registrars in the policy for which the presence of an electronic signature of images is not checked                   | 104
having transports other than `docker` in the list of supported ones (transport for receiving images from the registrar)      | 105
.fi
.IP "" 0
.TP
files for binding registrars to servers storing electronic signatures (default binding file \fBdefault\.yaml\fR and registrar binding files \fB*\.yaml\fR of the \fBregistries\.d\fR directory)\. Availability (number) of users:

.IP "" 4
.nf
User Control Parameter                                                                    | Metric Weight
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-|\-\-\-\-\-\-\-\-\-\-\-\-\-
not using signature store `http://sigstore\.local:81/sigstore/` as default signature store | 106
.fi
.IP "" 0
.IP "\[ci]" 4
user group control
.TP
presence of users with images, but not included in the \fBpodman\fR group:


.IP "" 0
.IP "" 4
.nf
User control parameter | Metric weight
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-|\-\-\-\-\-\-\-\-\-\-\-\-\-
presence of users with images, but not included in the `podman` group | 101
.fi
.IP "" 0
.IP "" 4
.nf
* presence of users of the `podman` group (excluding those in the `podman_dev` group):
.fi
.IP "" 0
.IP "" 4
.nf
User control parameter | Metric weight
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-|\-\-\-\-\-\-\-\-\-\-\-\-\-
in the `wheel` group                                                         | 107
having the `\.config/containers/` directory open for writing and modification | 90 * `share_of_offenders`
not having the `\.config/containers/storage\.conf` configuration file          | 90 * `share_of_offenders
.fi
.IP "" 0
.P
\fBshare_of_violators\fR is calculated as: \fBnumber_of_violators / number_of_users_in_podman_group\fR
.P
All metric weights are summed up and a final metric is formed\.
.SH "OPTIONS"
When the \fB\-M Email\fR flag is specified, the final message is sent to the specified user\.
.P
The danger level is determined at startup by the flags:
.TP
for system logs:

.IP "" 4
.nf
Level name |Level| Prefix   | Flag | Recommended interval value
\-\-\-\-\-\-\-\-\-\-\-|\-\-\-\-\-|\-\-\-\-\-\-\-\-\-\-|\-\-\-\-\-\-|\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
emergency  | 7   | Crash    | `\-a` | do not specify
fatal      | 6   | Fatal    | `\-f` | do not specify
critical   | 5   | Critical | `\-c` | 100
high       | 4   | Heigh    | `\-h` | 0
average    | 3   | Middle   | `\-m` | do not specify
Low        | 2   | Low      | `\-l` | do not specify
Debug      | 1   | Debug    | `\-d` | do not specify
.fi
.IP "" 0
.TP
for the \fBicigna\fR server:

.IP "" 4
.nf
Level name |Level|  Prefix  | Flag | Recommended interval value
\-\-\-\-\-\-\-\-\-\-\-|\-\-\-\-\-|\-\-\-\-\-\-\-\-\-\-|\-\-\-\-\-\-|\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
Critical   | 2   | Critical | `\-c` | 100
Warning    | 1   | Warning  | `\-w` | 0
.fi
.IP "" 0
.P
Any parameter may be missing\. In this case, it is not considered when viewing the compliance of the received metric with the intervals\.
.P
The parameter values ​​have the interval format described in the nagios documentation: Threshold and Ranges \fIhttps://nagios\-plugins\.org/doc/guidelines\.html#THRESHOLDFORMAT\fR\.
.P
General description:
.P
\fB[@]start:end\fR
.P
Notes:
.IP "\[ci]" 4
\fBstart\fR \(<= \fBend\fR
.IP "\[ci]" 4
\fBstart\fR and \fB:\fR are not required if \fBstart=0\fR
.IP "\[ci]" 4
if the interval is specified in the format \fBstart:\fR and the end is not specified, then the end of the interval is considered to be infinity \fBꝏ\fR
.IP "\[ci]" 4
to indicate negative infinity (\fB\-ꝏ\fR) use \fB~\fR
.IP "\[ci]" 4
the trigger fires when the metric value is \fBOUTSIDE THE SPECIFIED INTERVAL\fR (\fBstart and end points are included in the interval\fR)
.IP "\[ci]" 4
if the interval begins with the \fB@\fR symbol, then the condition is inverted \- the trigger fires when the metric value is \fBIN THE SPECIFIED INTERVAL\fR (start and end points are included in the interval)
.IP "" 0
.P
Examples of possible formats:
.IP "" 4
.nf
Interval format | Description of the trigger condition
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-|\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
100             | metrica < 0 || metrica > 100 (outside the range 0\-100)
100:            | metrica < 100 (outside the range 100\-ꝏ)
~:100           | metrica > 100 (outside the range \-ꝏ\-100)
20\-100          | metrica < 20 || metrica > 100 (outside the range 20\-100)
@20\-100         | metrica >= 20 && metrica <= 100 (in the range 20\-100)
.fi
.IP "" 0
.SS "System logs"
For system logs, the danger level is determined for each message\. The danger level intervals specified by the parameters are viewed in order from highest to lowest\. The message level is determined by the first match found (remember that the trigger is triggered when the metric is OUTSIDE the interval)\. If no match is found, the message is not output to the system log\.
.P
Based on the level found, the priority of the message and its tag (prefix) are determined\. A message with the specified priority and tag is sent to the system log using the logger command:
.IP "" 4
.nf
# logger \-p priority \-t tag "tag: message"
.fi
.IP "" 0
.P
In addition to the main message for \fBicigna\fR, the following are generated:
.IP "\[ci]" 4
a list of offending users;
.IP "\[ci]" 4
shortened messages for detail level \fB1\fR\.
.IP "" 0
.SS "icigna logs"
The formats of messages and exit codes of the plugin are described in Plugin Output for Nagios \fIhttps://nagios\-plugins\.org/doc/guidelines\.html#PLUGOUTPUT\fR\.
.P
The severity level for icigna logs is determined by the TOTAL metric\. The total metric is determined to determine the level and compared with the intervals specified by the flags
.IP "\[ci]" 4
\fB\-c\fR \- \fBCritical\fR
.IP "\[ci]" 4
\fB\-w\fR \- \fBWarning\fR
.IP "" 0
.P
If no match is found, \fBicigna\fR prints the message:
.IP "" 4
.nf
POLICY OK: Containerization policies are not violated
.fi
.IP "" 0
.P
The program exit code (which is processed on the \fBicigna\fR server side) is \fB0\fR\.
.P
The log format for \fBicigna\fR depends on the level of detail specified by the \fB\-v[vv]\fR flag (see Verbose Output \fIhttps://nagios\-plugins\.org/doc/guidelines\.html#AEN41\fR):
.IP "" 4
.nf
Flag | Level
\-\-\-\-\-|\-\-\-\-\-\-\-\-
none | 0
\-v   | 1
\-vv  | 2
\-vvv | 3
\|\.\|\.\|\.  | 3
.fi
.IP "" 0
.P
For all levels, a prefix message of the following format is generated:
.IP "" 4
.nf
POLICY $prefix:
.fi
.IP "" 0
.P
Where \fBprefix\fR takes the following values ​​depending on the severity level:
.IP "\[ci]" 4
\fB\-c\fR \- \fBCritical\fR
.IP "\[ci]" 4
\fB\-w\fR \- \fBWarning\fR
.IP "" 0
.P
If the level of detail is \fB0\fR, a shortened message is output\.
.IP "" 4
.nf
POLICY $prefix: Violation of user containerization policies \fIusers\fR
.fi
.IP "" 0
.P
Where \fBusers\fR is a list of users for whom violations were detected\.
.P
If the detail level is \fB1\fR, then the first detail level from the list of shortened messages generated during the formation of system logs is added to the message with the prefix \fIThere are users:\fR\.
.IP "" 4
.nf
POLICY $prefix: Violation of user containerization policies $users | There are users:
shortened message
\|\.\|\.\|\.
.fi
.IP "" 0
.P
If the detail level is \fB2\fR, then the second detail level from the list of full messages generated during the formation of system logs is added to the message\.
.IP "" 4
.nf
POLICY $prefix: Violation of user containerization policies $users | There are users:
shortened message
\|\.\|\.\|\.
shortened message |
full message
\|\.\|\.\|\.
.fi
.IP "" 0
.P
After displaying messages, the plugin exits with the exit code:
.IP "\[ci]" 4
\fBCritical\fR \- \fB2\fR
.IP "\[ci]" 4
\fBWarning\fR \- \fB1\fR
.IP "" 0
.SS "Starting a service via systemd/Timers"
In addition to starting the script via \fBnagios\fR, the script can be started via \fBsystemd/Timers\fR\. The package includes the systemd files \fBpodsec\-inotify\-check\-policy\.service\fR, \fBpodsec\-inotify\-check\-policy\.timer\fR\. The service file \fBpodsec\-inotify\-check\-policy\.service\fR describes a line in the \fBExecStart\fR parameter describing the startup mode of the \fBpodsec\-inotify\-check\-policy\fR script\. The script is started with the flags \fB\-vvv \-c 100\fR \- display detailed information, all messages have the \fBc\fR level \- critical\. If incorrect policy settings are detected during the script\'s operation, they are output to the system log and sent by mail to the system administrator (\fBroot\fR)\.
.P
The schedule for starting the service \fBpodsec\-inotify\-check\-policy\.service\fR is described in the \fBOnCalendar\fR parameter of the schedule file \fBpodsec\-inotify\-check\-policy\.timer\fR\. The service is called every hour\.
.P
By default, the service start timer is disabled\. To enable it, enter the command:
.IP "" 4
.nf
# systemctl enable \-\-now podsec\-inotify\-check\-policy\.timer
.fi
.IP "" 0
.P
If you need to change the script startup mode, edit the \fBOnCalendar\fR parameter of the schedule file \fBpodsec\-inotify\-check\-policy\.timer\fR\.
.SH "EXAMPLES"
Analyze policy policies with maximum detail\. Critical level (\fBnagios\fR, \fBsystem\fR) \fB>100\fR\. Warning level (\fBnagios\fR) \fB>0\fR\. Low level (\fBsystem\fR) \fB>0\fR\.
.IP "" 4
.nf
# podsec\-inotify\-check\-policy \-vvv \-w 0 \-h 0 \-c 100
POLICY Critical(18): Violation of containerization policies for users "imagedeveloper" "k8s\-user1" "kaf" "kafpodman" "podmanuser" "root" "securityadmin" "user" "user1" | There are users:
outside the podman group,
able to receive any image
able to receive a local image without a signature
able to receive any image without a signature
able to receive any image via a prohibited transport
not using a local signature keeper
included in the wheel group
not having a configuration file
able to change the configuration" |
Critical(101): Users "kafpodman" have images, but are not in the \'podman\' group
Critical(102): Users "user" have defaultPolicy!=reject in policy\.json, but are not in the \'podman_dev\' group
Critical(103): Users "user" do not have registry\.local in the list of registrars for which the presence of an electronic signature of images is checked
Critical(104): Users "root" "kaf" "kafpodman" "podmanuser" "securityadmin" "user1" have registrars in the policy for which the presence of an electronic signature of images is not checked
Critical(105): Users "user" have transports other than docker in the supported list
Critical(106): Users "imagedeveloper" "user" do not use signature store http://sigstore\.local:81/sigstore/ as default signature store
Critical(107): Users "kaf" "securityadmin" are members of groups \'podman\' and \'wheel\'
High(72): Users "k8s\-user1" "kaf" "securityadmin" "user1" do not have a \.config/containers/storage\.conf configuration file
High(18): Users "user" have a writable \.config/containers configuration directory
.fi
.IP "" 0
.P
Program exit code is \fB2\fR\.
.SH "SECURITY CONSIDERATIONS"
.SH "SEE ALSO"
.IP "\[ci]" 4
Nagios Plugins\. Development Guidelines \fIhttps://nagios\-plugins\.org/doc/guidelines\.html#PLUGOUTPUT\fR
.IP "" 0
.SH "AUTHOR"
Kostarev Alexey, Basealt LLC kaf@basealt\.ru
