.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "PODSEC\-INOTIFY\-CHECK\-KUBEAPI" "1" "October 2024" ""
.SH "NAME"
\fBpodsec\-inotify\-check\-kubeapi\fR \- kube\-apiserver control\-plane API audit monitoring script
.SH "SYNOPSIS"
\fBpodsec\-inotify\-check\-kubeapi [\-d]\fR
.SH "DESCRIPTION"
The script monitors the \fB/etc/kubernetes/audit/audit\.log\fR file for auditing the \fBkube\-apiserver\fR API\.
.P
The audit policy is located in the \fB/etc/kubernetes/audit/policy\.yaml\fR file:
.IP "" 4
.nf
apiVersion: audit\.k8s\.io/v1
kind: Policy
omitManagedFields: true
rules:
# do not log requests to the following
\- level: None
  nonResourceURLs:
  \- "/healthz*"
  \- "/logs"
  \- "/metrics"
  \- "/swagger*"
  \- "/version"
  \- "/readyz"
  \- "/livez"

\- level: None
  users:
    \- system:kube\-scheduler
    \- system:kube\-proxy
    \- system:apiserver
    \- system:kube\-controller\-manager
    \- system:serviceaccount:gatekeeper\-system:gatekeeper\-admin

\- level: None
  userGroups:
    \- system:nodes
    \- system:serviceaccounts
    \- system:masters

# limit level to Metadata so token is not included in the spec/status
\- level: Metadata
  omitStages:
  \- RequestReceived
  resources:
  \- group: authentication\.k8s\.io
    resources:
    \- tokenreviews

# extended audit of auth delegation
\- level: RequestResponse
  omitStages:
  \- RequestReceived
  resources:
  \- group: authorization\.k8s\.io
    resources:
    \- subjectaccessreviews

# log changes to pods at RequestResponse level
\- level: RequestResponse
  omitStages:
  \- RequestReceived
  resources:
  \- group: "" # core API group; add third\-party API services and your API services if needed
    resources: ["pods"]
    verbs: ["create", "patch", "update", "delete"]

# log everything else at Metadata level
\- level: Metadata
  omitStages:
  \- RequestReceived
.fi
.IP "" 0
.P
Current settings log all requests from "non\-system" users (including anonymous ones) to \fBkubernetes\fR resources\.
.P
The script selects all requests that resulted in a code greater than \fB400\fR \- access denied\. All these facts are recorded in the system log and accumulated in the log file \fB/var/lib/podsec/u7s/log/kubeapi/forbidden\.log\fR, which is periodically transmitted via post to the system administrator\.
.SH "OPTIONS"
.IP "\[ci]" 4
\fB\-d\fR \- the script runs in daemon mode, performing online monitoring of the file \fB/etc/kubernetes/audit/audit\.log\fR and recording the facts of requests with access denied in the system log and the log file \fB/var/lib/podsec/u7s/log/kubeapi/forbidden\.log\fR\.
.IP "\[ci]" 4
\fB\-m\fR \- the script sends the log file \fB/var/lib/podsec/u7s/log/kubeapi/forbidden\.log\fR by mail to the system administrator (user \fBroot\fR) and resets the log file\.
.IP "" 0
.P
In addition to this script, the package includes:
.TP
the service description file \fB/lib/systemd/system/podsec\-inotify\-check\-kubeapi\.service\fR\. To start it, you need to run the commands:

.IP "" 4
.nf
# systemctl enable podsec\-inotify\-check\-kubeapi\.service
# systemctl start podsec\-inotify\-check\-kubeapi\.service
.fi
.IP "" 0
.IP "\[ci]" 4
The schedule file \fB/lib/systemd/system/podsec\-inotify\-check\-kubeapi\-mail\.timer\fR, which specifies the start schedule for the service \fB/lib/systemd/system/podsec\-inotify\-check\-kubeapi\-mail\.timer\fR in the \fBOnCalendar\fR parameter\. The timer is called every hour\.
.IP "" 0
.P
By default, the service startup timer is disabled\. To enable it, enter the command:
.IP "" 4
.nf
# systemctl enable \-\-now podsec\-inotify\-check\-kubeapi\-mail\.timer
.fi
.IP "" 0
.P
If you need to change the script startup mode, edit the \fBOnCalendar\fR parameter of the \fBpodsec\-inotify\-check\-kubeapi\-mail\.timer\fR schedule file\.
.SH "EXAMPLE"
\fBpodsec\-inotify\-check\-kubeapi \-d\fR
.P
\fBpodsec\-inotify\-check\-kubeapi \-m\fR
.SH "SECURITY CONSIDERATIONS"
In addition to monitoring access denials, other suspicious activity can be monitored\.
.SH "SEE ALSO"
.IP "\[ci]" 4
Auditing \fIhttps://kubernetes\.io/docs/tasks/debug/debug\-cluster/audit/\fR
.IP "\[ci]" 4
kube\-apiserver Audit Configuration (v1) \fIhttps://kubernetes\.io/docs/reference/config\-api/apiserver\-audit\.v1/\fR
.IP "\[ci]" 4
Kubernetes Audit Logs \- Best Practices And Configuration \fIhttps://signoz\.%20io/blog/kubernetes\-audit\-logs/\fR
.IP "\[ci]" 4
How to monitor Kubernetes audit logs \fIhttps://www\.datadoghq\.com/blog/monitor\-kubernetes\-audit\-logs/#monitor\-api\-authentication\-issues\fR
.IP "" 0
.SH "AUTHOR"
Alexey Kostarev, Basalt LLC kaf@basealt\.ru
