.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "PODSEC\-INOTIFY\-CHECK\-CONTAINERS" "1" "October 2024" ""
.SH "NAME"
\fBpodsec\-inotify\-check\-containers\fR \- check for changes in critical files of rootfull and rootless containers
.SH "SYNOPSIS"
\fBpodsec\-inotify\-check\-containers\fR
.SH "DESCRIPTION"
Script:
.IP "\[ci]" 4
creates a list of \fBrootless\fR and \fBrootfull\fR container directories existing in the system,
.IP "\[ci]" 4
runs a check for addition, deletion, and modification of files in container directories,
.IP "\[ci]" 4
sends a notification about the change to the system log\.
.IP "" 0
.P
The script starts two directory monitoring processes:
.IP "\[ci]" 4
monitoring of adding users in the \fB/home/\fR directory, adding containers in the \fB*/storage/overlay/\fR \fBrootless\fR and \fBrootfull\fR user directories (the list is generated in the \fB/tmp/inotifyMonitor\.tmp\fR file);
.IP "\[ci]" 4
monitoring of file changes in the \fBrootless\fR and \fBrootfull\fR user containers (the list is generated in the \fB/tmp/inotifyOverlays\.tmp\fR file)\.
.IP "" 0
.P
When the monitored directories change, the first process generates lists in the \fB/tmp/inotifyMonitor\.tmp\fR, \fB/tmp/inotifyOverlays\.tmp\fR monitoring files, restarts itself and the second process of monitoring file changes in containers\.
.P
The second process of changing files in containers monitors all files and directories except for files and directories in the root directories \fB/var/\fR, \fB/proc/\fR, \fB/tmp/\fR, \fB/run/\fR, which can be intensively changed when containers are running by container services\.
.P
Changes in the directories \fB/home/\fR, \fB/root/\fR, \fB/etc/\fR are logged to the system log as warnings (level \fBWarning\fR)\. Changes in other directories are logged to the system log as critical (level \fBCritical\fR)\.
.P
Messages in the system log have the following format: \fBAn event <event> occurred in the container <container> [in home directory|in configuration directory] on the file <file>\fR
.SH "SECURITY CONSIDERATIONS"
.IP "\[ci]" 4
This script is run by the service \fBpodsec\-inotify\-check\-containers\.service\fR\.
.IP "" 0
.SH "EXAMPLES"
If containers are deployed in the system and you need to monitor file modifications inside these containers, run the service \fBpodsec\-inotify\-check\-containers\.service\fR: \fB# systemctl enable \-\-now podsec\-inotify\-check\-containers\.service\fR
.SH "AUTHOR"
.IP "\[ci]" 4
Burykin Nikolay, ALT Linux Team, bne@altlinux\.org
.IP "\[ci]" 4
Kostarev Alexey, ALT Linux Team, kaf@basealt\.ru
.IP "" 0

