.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PODSEC\-K8S\-RBAC\-CREATE\-KUBECONFIG" "1" "March 2023" "" ""
.
.SH "NAME"
\fBpodsec\-k8s\-rbac\-create\-kubeconfig\fR \- создание RBAC пользователя
.
.SH "SYNOPSIS"
\fBpodsec\-k8s\-rbac\-create\-kubeconfig имя_пользователя [группа \|\.\|\.\|\.]\fR
.
.SH "DESCRIPTION"
Скрипт производит:
.
.SH "EXAMPLES"
\fBpodsec\-k8s\-rbac\-create\-kubeconfig userrbac1\fR
.
.SH "SECURITY CONSIDERATIONS"

