.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PODSEC\-K8S\-RBAC\-CREATE\-USER" "1" "March 2023" "" ""
.
.SH "NAME"
\fBpodsec\-k8s\-rbac\-create\-user\fR \- создание RBAC\-пользователя
.
.SH "SYNOPSIS"
\fBpodsec\-k8s\-rbac\-create\-user имя_пользователя\fR
.
.SH "DESCRIPTION"
Скрипт:
.
.IP "\[ci]" 4
создает RBAC пользователя
.
.IP "\[ci]" 4
создает в домашнем директории каталог \.kube
.
.IP "\[ci]" 4
устанавливаются соответствующие права доступа к каталогам\.
.
.IP "" 0
.
.SH "EXAMPLES"
\fBpodsec\-k8s\-rbac\-create\-user userrbac1\fR
.
.SH "SECURITY CONSIDERATIONS"

