.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PODSEC\-K8S\-RBAC\-BINDROLE" "1" "March 2023" "" ""
.
.SH "NAME"
\fBpodsec\-k8s\-rbac\-bindrole\fR \- привязывание пользователя к кластерной или обычной роли
.
.SH "SYNOPSIS"
\fBpodsec\-k8s\-rbac\-bindrole имя_пользователя role|role=clusterrole|clusterrole роль имя_связки_роли [namespace]\fR
.
.SH "DESCRIPTION"
Скрипт производит привязку пользователя к обычной или кластерной роли используя имя\fIсвязки\fRроли\.
.
.SH "OPTIONS"
.
.IP "\[ci]" 4
\fBимя_пользователя\fR должно быть создано командой \fBpodsec\-k8s\-rbac\-create\-user\fR и сконфигурировано на доступ к кластеру командой \fBpodsec\-k8s\-rbac\-create\-kubeconfig\fR;
.
.IP "\[ci]" 4
\fBтип роли\fR может принимать следующие значения:
.
.IP "" 0
.
.P
\~\~\~\~* \fBrole\fR \- пользователь привязывется к \fBобычной роли\fR с именем \fB<роль>\fR (параметр \fBnamespace\fR в этом случае обязателен);
.
.P
\~\~\~\~* \fBrole=clusterrole\fR \- пользователь привязывется к \fBобычной роли\fR используя \fBкластерную роль\fR с именем \fB<роль>\fR (параметр \fBnamespace\fR в этом случае обязателен);
.
.P
\~\~\~\~* \fBclusterrole\fR \- пользователь привязывется к \fBкластерной роли\fR используя \fBкластерную роль\fR с именем \fB<роль>\fR (параметр \fBnamespace\fR в этом случае должен отсутствовать)\.
.
.IP "\[ci]" 4
\fBроль\fR \- имя обычной или кластерной роли в зависимости от предыдущего параметра;
.
.IP "\[ci]" 4
\fBимя_связки_роли\fR \- имя объекта класса \fBrolebindings\fR или \fBclusterrolebindings\fR в зависимости от параметра \fBтип роли\fR\. В рамках этого объекта к кластерной или обычной роли могут быть привязаны несколько пользователей\.
.
.IP "\[ci]" 4
\fBnamespace\fR \- имя \fBnamespace\fR для обычной роли\.
.
.IP "" 0
.
.SH "EXAMPLES"
.
.nf


podsec\-k8s\-rbac\-bindrole k8s\-user1 clusterrole edit sysadmin
podsec\-k8s\-rbac\-bindrole k8s\-user1 clusterrole view sysview
podsec\-k8s\-rbac\-bindrole k8s\-user1 role=clusterrole edit sysadmin default
podsec\-k8s\-rbac\-bindrole k8s\-user1 role=clusterrole system:basic\-user basic\-user default
podsec\-k8s\-rbac\-bindrole k8s\-user1 role=clusterrole system:basic\-user basic\-user smf
.
.fi
.
.SH "SECURITY CONSIDERATIONS"
.
.SH "SEE ALSO"
.
.IP "\[ci]" 4
Генерация сертификатов, создание рабочих мест администратора безопасности средства контейнеризации, администраторов информационной (автоматизированной) системы и назначение им RBAC\-ролей \fIhttps://github\.com/alt\-cloud/podsec/blob/master/k8s/RBAC/addUser/README\.md\fR;
.
.IP "\[ci]" 4
Описание основных классов ролей кластера (Roles, ClusterRoles) и механизмов из связываения с субъектами \fIhttps://github\.com/alt\-cloud/podsec/blob/master/k8s/RBAC/addUser/rolesDescribe\.md\fR;
.
.IP "\[ci]" 4
Настройка рабочих мест администраторов информационной (автоматизированной) системы (ClusterRole) \fIhttps://github\.com/alt\-cloud/podsec/blob/master/k8s/RBAC/addUser/clusterroleBinding\.md\fR;
.
.IP "\[ci]" 4
Настройка рабочих мест администраторов проектов (Role) \fIhttps://github\.com/alt\-cloud/podsec/blob/master/k8s/RBAC/addUser/clusterroleBinding\.md\fR;
.
.IP "\[ci]" 4
Настройка других ролей \fIhttps://github\.com/alt\-cloud/podsec/blob/master/k8s/RBAC/addUser/clusterroleBinding\.md\fR\.
.
.IP "" 0

