.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "PODSEC\-K8S\-RBAC\-CREATE\-KUBECONFIG" "" "February 2024" ""
.SH "NAME"
\fBpodsec\-k8s\-rbac\-create\-kubeconfig\fR
.P
podsec\-k8s\-rbac\-create\-kubeconfig(1) \-\- создание ключей, сертификатов и файла конфигурации RBAC\-пользователя
.SH "SYNOPSIS"
\fBpodsec\-k8s\-rbac\-create\-kubeconfig имя_пользователя[@<имя_удаленного_пользователя>] [группа \|\.\|\.\|\.]\fR
.SH "DESCRIPTION"
Скрипт должен вызываться \fIадминистратором безопасности средства контейнеризации\fR\.
.P
Для \fBrootless\fR решения имя удаленного пользователя принимается \fBu7s\-admin\fR\.
.P
Для \fBrootfull\fR решения необходимо после символа \fB@\fR указать имя удаленного пользователя\.
.P
Скрипт в каталоге \fB~имя_пользователя/\.kube\fR производит:
.IP "\[ci]" 4
Создании личного (private) ключа пользователя (файл \fBимя_пользователя\.key\fR)\.
.IP "\[ci]" 4
Создание запроса на подпись сертификата (CSR) (файл \fBимя_пользователя\.key\fR)\.
.IP "\[ci]" 4
Запись запроса на подпись сертификата CSR в кластер\.
.IP "\[ci]" 4
Подтверждение запроса на подпись сертификата (CSR)\.
.IP "\[ci]" 4
Создание сертификата (файл \fBимя_пользователя\.crt\fR)\.
.IP "\[ci]" 4
Проверку корректности сертификата
.IP "\[ci]" 4
Формирование файла конфигурации пользователя (файл \fBconfig\fR)
.IP "\[ci]" 4
Добавление контекста созданного пользователя
.IP "" 0
.SH "EXAMPLES"
\fBpodsec\-k8s\-rbac\-create\-kubeconfig k8s\-user1\fR
.SH "SECURITY CONSIDERATIONS"
.SH "SEE ALSO"
.IP "\[ci]" 4
Генерация сертификатов, создание рабочих мест администратора безопасности средства контейнеризации, администраторов информационной (автоматизированной) системы и назначение им RBAC\-ролей \fIhttps://github\.com/alt\-cloud/podsec/blob/master/k8s/RBAC/addUser/README\.md\fR;
.IP "\[ci]" 4
Создание рабочих мест и сертификатов \fIhttps://github\.com/alt\-cloud/podsec/blob/master/k8s/RBAC/addUser/clusterroleBinding\.md\fR\.
.IP "" 0
.SH "AUTHOR"
Костарев Алексей, Базальт СПО kaf@basealt\.ru
