.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PODSEC\-K8S\-RBAC\-CREATE\-KUBECONFIG" "" "May 2023" "" ""
.
.SH "NAME"
\fBpodsec\-k8s\-rbac\-create\-kubeconfig\fR
.
.P
podsec\-k8s\-rbac\-create\-kubeconfig(1) \-\- создание ключей, сертификатов и файла конфигурации RBAC\-пользователя
.
.SH "SYNOPSIS"
\fBpodsec\-k8s\-rbac\-create\-kubeconfig имя_пользователя[@<имя_удаленного_пользователя>] [группа \.\.\.]\fR
.
.SH "DESCRIPTION"
Скрипт должен вызываться \fIадминистратором безопасности средства контейнеризации\fR\.
.
.P
Для \fBrootless\fR решения имя удаленного пользователя принимается \fBu7s\-admin\fR\.
.
.P
Для \fBrootfull\fR решения необходимо после символа \fB@\fR указать имя удаленного пользователя\.
.
.P
Скрипт в каталоге \fB~имя_пользователя/\.kube\fR производит:
.
.IP "\(bu" 4
Создании личного (private) ключа пользователя (файл \fBимя_пользователя\.key\fR)\.
.
.IP "\(bu" 4
Создание запроса на подпись сертификата (CSR) (файл \fBимя_пользователя\.key\fR)\.
.
.IP "\(bu" 4
Запись запроса на подпись сертификата CSR в кластер\.
.
.IP "\(bu" 4
Подтверждение запроса на подпись сертификата (CSR)\.
.
.IP "\(bu" 4
Создание сертификата (файл \fBимя_пользователя\.crt\fR)\.
.
.IP "\(bu" 4
Проверку корректности сертификата
.
.IP "\(bu" 4
Формирование файла конфигурации пользователя (файл \fBconfig\fR)
.
.IP "\(bu" 4
Добавление контекста созданного пользователя
.
.IP "" 0
.
.SH "EXAMPLES"
\fBpodsec\-k8s\-rbac\-create\-kubeconfig k8s\-user1\fR
.
.SH "SECURITY CONSIDERATIONS"
.
.SH "SEE ALSO"
.
.IP "\(bu" 4
Генерация сертификатов, создание рабочих мест администратора безопасности средства контейнеризации, администраторов информационной (автоматизированной) системы и назначение им RBAC\-ролей \fIhttps://github\.com/alt\-cloud/podsec/blob/master/k8s/RBAC/addUser/README\.md\fR;
.
.IP "\(bu" 4
Создание рабочих мест и сертификатов \fIhttps://github\.com/alt\-cloud/podsec/blob/master/k8s/RBAC/addUser/clusterroleBinding\.md\fR\.
.
.IP "" 0
.
.SH "AUTHOR"
Костарев Алексей, Базальт СПО kaf@basealt\.ru
