.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PODSEC\-K8S\-RBAC\-CREATE\-REMOTEPLACE" "1" "March 2023" "" ""
.
.SH "NAME"
\fBpodsec\-k8s\-rbac\-create\-remoteplace\fR \- создание удаленного рабочего места
.
.SH "SYNOPSIS"
\fBpodsec\-k8s\-rbac\-create\-remoteplace ip\-адрес\fR
.
.SH "DESCRIPTION"
Скрипт производит настройку удаленного рабочего места пользователя путем копирования его конфигурационного файла\.
.
.SH "EXAMPLES"
\fBpodsec\-k8s\-rbac\-create\-remoteplace 192\.168\.122\.234\fR
.
.SH "SECURITY CONSIDERATIONS"
Для повышения безопасности работы с кластером имеет смысл вынести рабочие места пользователей на отдельные рабочие места\.
.
.P
Администратор безопасности средства контейнеризации копирует с помощью этого скрипта файл конфигурации \fB\.kube/config\fR на свое работчее место и получает возможность удалееной работы с кластером\.
.
.P
При создании рабочих мест администратор безопасности средства контейнеризации на своем рабочем месте с помощью скриптов \fBpodsec\-k8s\-rbac\-create\-user\fR, \fBpodsec\-k8s\-rbac\-create\-kubeconfig\fR, \fBpodsec\-k8s\-rbac\-bindrole\fR создает домашние директории и конфигурационный файл \fB\.kube/config\fR пользователя, создавая у себя контекст созданного пользователя\. Переключаясь в контекст пользователя администратор безопасности средства контейнеризации может тестировать права доступа созданного пользователя\.
.
.P
Пользователь на своем удаленном рабочем месте с помощью этого скрипта копирует конфигурационный файл себе\.
.
.P
Домашний каталог созданного пользователя на рабочем месте администратора безопасности средства контейнеризации удаляется\.
.
.IP "\[ci]" 4
Конфигурационный файл \fB\.kube/config\fR с помощью
.
.IP "" 0

