.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PODSEC\-K8S\-RBAC\-UNBINDROLE" "1" "March 2023" "" ""
.
.SH "NAME"
\fBpodsec\-k8s\-rbac\-unbindrole\fR \- отвязывание пользователя от кластерной или обычной роли
.
.SH "SYNOPSIS"
\fBpodsec\-k8s\-rbac\-unbindrole имя_пользователя role|clusterrole роль имя_связки_роли [namespace]\fR
.
.SH "DESCRIPTION"
Скрипт:
.
.SH "EXAMPLES"
\fBpodsec\-k8s\-rbac\-unbindrole userrbac1 clusterrole edit smfeditor smf\fR
.
.SH "SECURITY CONSIDERATIONS"

