.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PODSEC\-CREATE\-PODMANUSERS" "" "March 2023" "" ""
.
.SH "NAME"
\fBpodsec\-create\-podmanusers\fR
.
.P
podsec\-create\-podmanusers \- скрипт создает пользователей образов контейнеров, обладающий с правами на запуск подписанных образов с домена registry\.local
.
.SH "SYNOPSIS"
podsec\-create\-podmanusers \fIимя_пользователя\fR \|\.\|\.\|\.
.
.SH "DESCRIPTION"
Cкрипт создает пользователей образов контейнеров, обладающий с правами на запуск подписанных образов с домена registry\.local\.
.
.SH "OPTIONS"
Скрипту параметрами передается список создаваемых пользователей\.
