.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PODSEC\-CREATE\-POLICY" "" "March 2023" "" ""
.
.SH "NAME"
\fBpodsec\-create\-policy\fR
.
.P
podsec\-create\-policy \- скрипт создает файлы политик и настраивает системные сервисы для работы podman в rootless режиме
.
.SH "SYNOPSIS"
podsec\-create\-policy \fIip\-адрес\fIрегистратора\fRи\fIсервера\fRподписей\fR
.
.SH "DESCRIPTION"
Cкрипт создает файлы политик и настраивает системные сервисы для работы podman в rootless режиме
