.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PODSEC\-SAVE\-OCI" "1" "May 2023" "" ""
.
.SH "NAME"
\fBpodsec\-save\-oci\fR \- архивация образов различных архитектур в указанный первым параметром каталог c последующим сжатием и формированием \fBxz\-oci\-архива\fR
.
.SH "SYNOPSIS"
\fBpodsec\-save\-oci каталог_архивирования_образов архитектура,архитектура,\.\.\.|all образ \.\.\.\fR
.
.SH "DESCRIPTION"
.
.SH "OPTIONS"
.
.IP "\(bu" 4
Скрипт производит архивацию образов в указанный первым параметром каталог
.
.IP "\(bu" 4
Второй параметры задает через запятую архивируемые архитектуры\. Если второй параметр имеет значение all архивируются все архитектуры: \fBamd64\fR, \fBarm64\fR, \fBarm ppc64le\fR, \fB386\fR\.
.
.IP "\(bu" 4
Скрипт производит загрузку образов, указанных 3\-м и последующими параметрами с регистратора \fBregistry\.altlinux\.org\fR в \fBcontainers\-storage:\fR системы с последующим помещением их в указанный первым параметром каталог в подкаталог с именем архитектуры \fB$ociDir/$arch\fR\. Для улучшения последующей компресии слои образа помещаются несжатыми (параметр \fB\-\-dest\-oci\-accept\-uncompressed\-layers\fR)
.
.IP "\(bu" 4
После окончания наполнения подкаталога архитектуры он архивируется, сжимается и помещается в файл \fB$ociDir/$arch\.tar\.xz\fR
.
.IP "" 0
.
.SH "EXAMPLES"
\fBpodsec\-save\-oci /tmp/ociDir/ amd64,arm64 k8s\-p10/flannel:v0\.19\.2 k8s\-p10/flannel\-cni\-plugin:v1\.2\.0\fR
.
.SH "SECURITY CONSIDERATIONS"
.
.IP "\(bu" 4
Так как скрипт производит загрузку образов различных архитектур последняя загруженная в containers\-storage: архитектура может отличаться от текущей архитектуры процессора\. При необходимости нужно будет произвести перезагрузку образов для рабочей архитектуры процессора
.
.IP "" 0
.
.SH "AUTHOR"
Костарев Алексей, Базальт СПО kaf@basealt\.ru
