.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PODSEC\-CREATE\-SERVICES" "" "March 2023" "" ""
.
.SH "NAME"
\fBpodsec\-create\-services\fR
.
.P
podsec\-create\-services \- скрипт поднимает сервисы docker\-registt и nginx для поддержкт регистратора докер образлв и сервера подписей образов
.
.SH "SYNOPSIS"
podsec\-create\-services
.
.SH "DESCRIPTION"
Чкрипт поднимает сервисы docker\-registt и nginx для поддержкт регистратора докер образлв и сервера подписей образов
