.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "PODSEC\-INOTIFY\-CHECK\-CONTAINERS" "1" "May 2024" ""
.SH "NAME"
\fBpodsec\-inotify\-check\-containers\fR \- проверка наличия изменений файлов в директориях rootless контейнерах
.SH "SYNOPSIS"
\fBpodsec\-inotify\-check\-containers\fR
.SH "DESCRIPTION"
Скрипт:
.IP "\[ci]" 4
создаёт список директорий rootless контейнеров, существующих в системе,
.IP "\[ci]" 4
запускает проверку на добавление,удаление, и изменение файлов в директориях контейнеров,
.IP "\[ci]" 4
отсылает уведомление об изменении в системный лог\.
.IP "" 0
.SH "SECURITY CONSIDERATIONS"
.IP "\[ci]" 4
Данный скрипт запускается сервисом inotify\-overlays\.service\.
.IP "" 0
.SH "EXAMPLES"
Если в системе развернуты контейнеры, и требуется следить за модификацией файлов внутри этих контейнеров, запустите сервис inotify\-overlays\.service: \fB# systemctl enable \-\-now inotify\-overlays\.service\fR По умолчанию в системный лог отсылаются сообщения двух типов: CRITICAL и INFO\. Для отключения логгирования событий типа INFO замените в скрипте /usr/bin/podsec\-inotify\-check\-containers значение переменной INFO_LOG с YES на NO\.
.SH "AUTHOR"
Burykin Nikolay, ALT Linux Team, bne@altlinux\.org
