.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PODSEC\-INOTIFY\-CHECK\-TRIVY\-K8S" "" "May 2023" "" ""
.
.SH "NAME"
\fBpodsec\-inotify\-check\-trivy\-k8s\fR
.
.SH "SYNOPSIS"
\fBpodsec\-inotify\-check\-trivy\-k8s\fR
.
.SH "DESCRIPTION"
.
.SH "OPTIONS"
.
.SH "EXAMPLES"
\fBpodsec\-inotify\-check\-trivy\-k8s\fR
.
.SH "SECURITY CONSIDERATIONS"
.
.SH "SEE ALSO"
.
.SH "AUTHOR"
Костарев Алексей, Базальт СПО kaf@basealt\.ru
