.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "PODSEC\-INOTIFY\-BUILD\-INVULNERABLE\-IMAGE" "1" "August 2024" ""
.SH "NAME"
\fBpodsec\-inotify\-build\-invulnerable\-image\fR \- скрипт создания docker\-образов и проверки их сканером безопасности trivy
.SH "SYNOPSIS"
\fBpodsec\-inotify\-build\-invulnerable\-image <имя_образа> [ <docker_файл> [ <каталог_контекста> [ <параметры_podman_build>\fR
.SH "DESCRIPTION"
Для корректной работы скрипта необходимо запустить сервис \fBtrivy\fR: \fBsystemctl enable \-\-now trivy\fR
.P
Скрипт производит создание docker\-образа \fBимя_образа\fR, описанного в \fBdocker_файл\fR (по умолчанию \fBDockerfile\fR) в каталоге \fBкаталог_контекста\fR (по умолчанию текущий) с параметрами сборки \fBпараметры_podman_build\fR\.
.P
После создание образа он проверяется на наличие уязвимостей сервисом \fBtrivy\fR\.
.SH "EXAMPLES"
\fBpodsec\-inotify\-build\-invulnerable\-image my\-first\-image\fR
.SH "SEE ALSO"
The all\-in\-one open source security scanner \fIhttps://trivy\.dev/\fR
.SH "AUTHOR"
Костарев Алексей, Базальт СПО kaf@basealt\.ru
