.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PODSEC\-INOTIFY\-CHECK\-CONTAINERS" "1" "July 2023" "" ""
.
.SH "NAME"
\fBpodsec\-inotify\-check\-containers\fR \- проверка наличия изменений файлов в директориях rootless контейнерах
.
.SH "SYNOPSIS"
\fBpodsec\-inotify\-check\-containers\fR
.
.SH "DESCRIPTION"
Скрипт:
.
.IP "\(bu" 4
создаёт список директорий rootless контейнеров, существующих в системе,
.
.IP "\(bu" 4
запускает проверку на добавление,удаление, и изменение файлов в директориях контейнеров,
.
.IP "\(bu" 4
отсылает уведомление об изменении в системный лог\.
.
.IP "" 0
.
.SH "SECURITY CONSIDERATIONS"
.
.IP "\(bu" 4
Данный скрипт запускается сервисом inotify\-overlays\.service\.
.
.IP "" 0
.
.SH "EXAMPLES"
Если в системе развернуты контейнеры, и требуется следить за модификацией файлов внутри этих контейнеров, запустите сервис inotify\-overlays\.service: `````` По умолчанию в системный лог отсылаются сообщения двух типов: CRITICAL и INFO\. Для отключения логгирования событий типа INFO замените в скрипте /usr/bin/podsec\-inotify\-check\-containers значение переменной INFO_LOG с YES на NO\.
.
.SH "AUTHOR"
Burykin Nikolay, ALT Linux Team, bne@altlinux\.org
