.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PODSEC\-INOTIFY\-CHECK\-POLICY" "1" "May 2023" "" ""
.
.SH "NAME"
\fBpodsec\-inotify\-check\-policy\fR \- Плугин проверяет образы на предмет их соответствия настройки политикам контейнеризации на узле
.
.SH "SYNOPSIS"
\fBpodsec\-inotify\-check\-images [\-v[vv]] [\-a интервал] [\-f интервал] \-c интервал \-h интервал [\-m интервал] х\-w интервалъ [\-l интервал] [\-d интервал]\fR
.
.SH "DESCRIPTION"
.
.SH "OPTIONS"
.
.SH "EXAMPLES"
\fBpodsec\-inotify\-check\-images\fR
.
.SH "SECURITY CONSIDERATIONS"
.
.SH "SEE ALSO"
.
.SH "AUTHOR"
Костарев Алексей, Базальт СПО kaf@basealt\.ru
