.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PODSEC\-K7S\-CREATE\-NODE" "1" "April 2023" "" ""
.
.SH "NAME"
\fBpodsec\-k7s\-create\-node\fR \- инициализация master\- или worker\-узла в rootless\-kubernetes (alt usernetes)
.
.SH "SYNOPSIS"
\fBpodsec\-k7s\-create\-node master|node\fR
.
.SH "DESCRIPTION"
Скрипт производит:
.
.SH "EXAMPLES"
\fBpodsec\-k7s\-create\-node master\fR
.
.SH "SECURITY CONSIDERATIONS"
.
.IP "\(bu" 4
Так как все работа с кластером производится по REST\-интерфейсу, то для обеспечения повышенных мер безопасности следует заводить \fBВСЕХ пользователей\fR, включая \fIадминистратор безопасности средства контейнеризации\fR \fBВНЕ узлов кластера\fR\. Для работы с кластером достаточно команды \fBkubectl\fR, входящую в пакет \fBkubernetes\-client\fR\.
.
.IP "" 0
.
.SH "SEE ALSO"
.
.IP "\(bu" 4
Kubernetes \fIhttps://www\.altlinux\.org/Kubernetes\fR;
.
.IP "\(bu" 4
Usernetes: Kubernetes without the root privileges \fIhttps://github\.com/rootless\-containers/usernetes\fR;
.
.IP "\(bu" 4
Настроика аудита API\-сервиса \fIhttps://github\.com/alt\-cloud/podsec/blob/master/k8s/RBAC/addUser/clusterroleBinding\.md\fR;
.
.IP "" 0
.
.SH "AUTHOR"
Костарев Алексей, Базальт СПО kaf@basealt\.ru
