.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "PODSEC\-K8S\-RBAC\-CREATE\-KUBECONFIG" "" "October 2024" ""
.SH "NAME"
\fBpodsec\-k8s\-rbac\-create\-kubeconfig\fR
.P
podsec\-k8s\-rbac\-create\-kubeconfig(1) \-\- create keys, certificates, and RBAC user configuration file
.SH "SYNOPSIS"
\fBpodsec\-k8s\-rbac\-create\-kubeconfig username[@<remote_username>] [group \|\.\|\.\|\.]\fR
.SH "DESCRIPTION"
The script should be called by the \fIcontainerization tool security administrator\fR\.
.P
For \fBrootless\fR solution, the remote user name is assumed to be \fBu7s\-admin\fR\.
.P
For \fBrootfull\fR solution, the remote user name must be specified after the \fB@\fR symbol\.
.P
The script in the \fB~username/\.kube\fR directory does the following:
.IP "\[ci]" 4
Create a private user key (file \fBusername\.key\fR)\.
.IP "\[ci]" 4
Create a certificate signing request (CSR) (file \fBusername\.key\fR)\.
.IP "\[ci]" 4
Write a CSR certificate signing request to the cluster\.
.IP "\[ci]" 4
Confirm a certificate signing request (CSR)\.
.IP "\[ci]" 4
Create a certificate (file \fBusername\.crt\fR)\.
.IP "\[ci]" 4
Check the correctness of the certificate
.IP "\[ci]" 4
Generate a user configuration file (file \fBconfig\fR)
.IP "\[ci]" 4
Add the context of the created user
.IP "" 0
.SH "EXAMPLES"
\fBpodsec\-k8s\-rbac\-create\-kubeconfig k8s\-user1\fR
.SH "SECURITY CONSIDERATIONS"
.SH "SEE ALSO"
.IP "\[ci]" 4
Generate certificates, create workstations for the containerization tool security administrator, administrators of the information (automated) system and assign them RBAC roles \fIhttps://github\.com/alt\-cloud/podsec/blob/master/k8s/RBAC/addUser/README\.md\fR;
.IP "\[ci]" 4
Creating workplaces and certificates \fIhttps://github\.com/alt\-cloud/podsec/blob/master/k8s/RBAC/addUser/clusterroleBinding\.md\fR\.
.IP "" 0
.SH "AUTHOR"
Kostarev Alexey, Basealt LLC kaf@basealt\.ru
