.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "PODSEC\-K8S\-RBAC\-BINDROLE" "1" "October 2024" ""
.SH "NAME"
\fBpodsec\-k8s\-rbac\-bindrole\fR \- bind user to cluster or regular role
.SH "SYNOPSIS"
\fBpodsec\-k8s\-rbac\-bindrole username role|role=clusterrole|clusterrole role role_bind_name [namespace]\fR
.SH "DESCRIPTION"
The script binds a user to a regular or cluster role using role_bind_name\.
.SH "OPTIONS"
.IP "\[ci]" 4
\fBusername\fR must be created by \fBpodsec\-k8s\-rbac\-create\-user\fR command and configured to access the cluster by \fBpodsec\-k8s\-rbac\-create\-kubeconfig\fR command;
.IP "\[ci]" 4
\fBrole type\fR can have the following values:
.IP "" 0
.P
\~\~\~\~* \fBrole\fR \- the user is bound to a \fBregular role\fR named \fB<role>\fR (the \fBnamespace\fR parameter is required in this case);
.P
\~\~\~\~* \fBrole=clusterrole\fR \- the user is bound to a \fBregular role\fR using a \fBcluster role\fR named \fB<role>\fR (the \fBnamespace\fR parameter is required in this case);
.P
\~\~\~\~* \fBclusterrole\fR \- the user is bound to a \fBcluster role\fR using a \fBcluster role\fR named \fB<role>\fR (the \fBnamespace\fR parameter must be absent in this case)\.
.IP "\[ci]" 4
\fBrole\fR \- the name of a regular or cluster role depending on the previous parameter;
.IP "\[ci]" 4
\fBrole_binding_name\fR \- the name of the \fBrolebindings\fR or \fBclusterrolebindings\fR class object depending on the \fBrole type\fR parameter\. Within this object, several users can be bound to a cluster or regular role\.
.IP "\[ci]" 4
\fBnamespace\fR \- the \fBnamespace\fR name for a regular role\.
.IP "" 0
.SH "EXAMPLES"
.nf
podsec\-k8s\-rbac\-bindrole k8s\-user1 clusterrole edit sysadmin
podsec\-k8s\-rbac\-bindrole k8s\-user1 clusterrole view sysview
podsec\-k8s\-rbac\-bindrole k8s\-user1 role=clusterrole edit sysadmin default
podsec\-k8s\-rbac\-bindrole k8s\-user1 role=clusterrole system:basic\-user basic\-user default
podsec\-k8s\-rbac\-bindrole k8s\-user1 role=clusterrole system:basic\-user basic\-user smf
.fi
.SH "SECURITY CONSIDERATIONS"
.SH "SEE ALSO"
.IP "\[ci]" 4
Generating certificates, creating workstations for the containerization tool security administrator, administrators of the information (automated) system and assigning them RBAC roles \fIhttps://github\.com/alt\-cloud/podsec/blob/master/k8s/RBAC/addUser/README\.md\fR;
.IP "\[ci]" 4
Description of the main classes of cluster roles (Roles, ClusterRoles) and mechanisms for binding with subjects \fIhttps://github\.com/alt\-cloud/podsec/blob/master/k8s/RBAC/addUser/rolesDescribe\.md\fR;
.IP "\[ci]" 4
Configuring workstations of administrators of the information (automated) system (ClusterRole) \fIhttps://github\.com/alt\-cloud/podsec/blob/master/k8s/RBAC/addUser/clusterroleBinding\.md\fR;
.IP "\[ci]" 4
Configuring project administrator workstations (Role) \fIhttps://github\.com/alt\-cloud/podsec/blob/master/k8s/RBAC/addUser/clusterroleBinding\.md\fR;
.IP "\[ci]" 4
Configuring other roles \fIhttps://github\.com/alt\-cloud/podsec/blob/master/k8s/RBAC/addUser/clusterroleBinding\.md\fR\.
.IP "" 0
.SH "AUTHOR"
Kostarev Alexey, Basalt LLC kaf@basealt\.ru
