.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "PODSEC\-K8S\-CREATE\-MASTER" "1" "October 2024" ""
.SH "NAME"
\fBpodsec\-k8s\-create\-master\fR \- initialize master node rootfull\-kubernetes
.SH "SYNOPSIS"
\fBpodsec\-k8s\-create\-master username_with_administrative_rights\fR
.SH "DESCRIPTION"
The script:
.IP "\[ci]" 4
Configure /etc/crio/crio\.conf to use \fBregistry\.local/k8s\-c10f1/pause:3\.9\fR as the pause image
.IP "\[ci]" 4
Start service \fBkubelet\fR
.IP "\[ci]" 4
Initialize \fBmaster node\fR of the cluster
.IP "\[ci]" 4
Configure \fBroot\fR to the role of \fIcluster administrator\fR
.IP "\[ci]" 4
Configure \fBspecified user\fR to the role of \fIcluster administrator\fR
.IP "\[ci]" 4
Configure audit of API service kubernetes\.
.IP "" 0
.P
After the script finishes running, don\'t forget to copy the worker node connection string from the cluster initialization stage output \fBkubeadm join xx\.xx\.xx\.xx:6443 \-\-token \|\.\|\.\|\. \-\-discovery\-token\-ca\-cert\-hash sha256:\|\.\|\.\|\.\fR You will need to use this command later to connect the cluster worker nodes\.
.SH "EXAMPLES"
\fBpodsec\-k8s\-create\-master securityadmin\fR
.SH "SECURITY CONSIDERATIONS"
.IP "\[ci]" 4
To work as a \fIcontainerization tool security administrator\fR, you need to create a user (for example, \fBsecurityadmin\fR) on the master node that belongs to the \fBpodman\fR, \fBwheel\fR groups\.
.IP "\[ci]" 4
Since all work with the cluster is performed via the REST interface, then to ensure increased security measures, you should create \fBALL users\fR, including the \fIcontainerization tool security administrator\fR \fBOUTSIDE the cluster nodes\fR\. To work with the cluster, the \fBkubectl\fR command, included in the \fBkubernetes\-client\fR package, is sufficient\.
.IP "" 0
.SH "SEE ALSO"
.IP "\[ci]" 4
Kubernetes \fIhttps://www\.altlinux\.org/Kubernetes\fR;
.IP "\[ci]" 4
Configuring API service audit \fIhttps://github\.com/alt\-cloud/podsec/blob/master/k8s/RBAC/addUser/clusterroleBinding\.md\fR;
.IP "" 0
.SH "AUTHOR"
Alexey Kostarev, Basalt LLC kaf@basealt\.ru
