version: "3"

services:

  init-certs:
    image: rootless-containers/usernetes
    entrypoint: /docker-entrypoint.sh
    extra_hosts:
      - registry.local:172.17.0.1
      - sigstore.local:172.17.0.1
    command:
      - unsudo
      - /home/u7s-admin/usernetes/common/cfssl.sh
      - --dir=/home/u7s-admin/.config/usernetes
      - --master=master
      - --node=node-crio1
      - --node=node-crio2
    privileged: true
    tty: true
    hostname: master
    volumes:
      - /lib/modules:/lib/modules
      - tls-master:/home/u7s-admin/.config/usernetes/master
      - tls-node-crio1:/home/u7s-admin/.config/usernetes/nodes.node-crio1
      - tls-node-crio2:/home/u7s-admin/.config/usernetes/nodes.node-crio2

  master:
    image: rootless-containers/usernetes
    extra_hosts:
      - registry.local:172.17.0.1
      - sigstore.local:172.17.0.1
    command:
      - --wait-init-certs
      - --start=u7s-master-with-etcd.target
      - --cidr=10.0.100.0/24
      - --publish=0.0.0.0:2379:2379/tcp
      - --publish=0.0.0.0:6443:6443/tcp
      - --cni=flannel
      - --cri=crio
    privileged: true
    tty: true
    ports:
      - 127.0.0.1:6443:6443
    hostname: master
    networks:
      - usernetes
    volumes:
      - /lib/modules:/lib/modules
      - tls-master:/home/u7s-admin/.config/usernetes/master

  node-crio1:
    image: rootless-containers/usernetes
    extra_hosts:
      - registry.local:172.17.0.1
      - sigstore.local:172.17.0.1
    command:
      - --wait-init-certs
      - --start=u7s-node.target
      - --cidr=10.0.101.0/24
      - --publish=0.0.0.0:10250:10250/tcp
      - --publish=0.0.0.0:8472:8472/udp
      - --cni=flannel
      - --cri=crio
    privileged: true
    tty: true
    networks:
      - usernetes
    hostname: node-crio1
    volumes:
      - /lib/modules:/lib/modules
      - tls-node-crio1:/home/u7s-admin/.config/usernetes/node
      - tls-master:/home/u7s-admin/.config/usernetes/master

  node-crio2:
    image: rootless-containers/usernetes
    extra_hosts:
      - registry.local:172.17.0.1
      - sigstore.local:172.17.0.1
    command:
      - --wait-init-certs
      - --start=u7s-node.target
      - --cidr=10.0.102.0/24
      - --publish=0.0.0.0:10250:10250/tcp
      - --publish=0.0.0.0:8472:8472/udp
      - --cni=flannel
      - --cri=crio
    privileged: true
    tty: true
    networks:
      - usernetes
    hostname: node-crio2
    volumes:
      - /lib/modules:/lib/modules
      - tls-node-crio2:/home/u7s-admin/.config/usernetes/node
      - tls-master:/home/u7s-admin/.config/usernetes/master

networks:
  usernetes:
volumes:
  tls-master:
    driver_opts:
      type: tmpfs
      device: tmpfs
      #o: "uid=1000"
  tls-node-crio1:
    driver_opts:
      type: tmpfs
      device: tmpfs
      #o: "uid=1000"
  tls-node-crio2:
    driver_opts:
      type: tmpfs
      device: tmpfs
      #o: "uid=1000"
