.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PODSEC\-NAGIOS\-PLUGINS\-CREATE\-NAGIOSUSER" "1" "March 2023" "" ""
.
.SH "NAME"
\fBpodsec\-nagios\-plugins\-create\-nagiosuser\fR \- создание пользователя nagios от имени которого запускаются nagios плугины
.
.SH "SYNOPSIS"
\fBpodsec\-nagios\-plugins\-create\-nagiosuser\fR
.
.SH "DESCRIPTION"
Создание пользователя nagios от имени которого запускаются nagios плугины\.
.
.SH "OPTIONS"
.
.SH "EXAMPLES"
\fBpodsec\-nagios\-plugins\-create\-nagiosuse\fR
.
.SH "SECURITY CONSIDERATIONS"
.
.IP "\[ci]" 4
Пользователь \fBnagios\fR входят в группу \fBwheel\fR и имеет возможноть запускать программы от имени \fBroot\fR\. Необходимо очень тщательно защищать пароль и закрытый ключ аналогичного пользвателя \fBnagios\fR на сервере, который имеет право запускать скрипты от своего имени на клиентской машине\.
.
.IP "" 0
.
.SH "SEE ALSO"
.
.SH "AUTHOR"
Костарев Алексей, Базальт СПО kaf@basealt\.ru
