.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PODSEC\-NAGIOS\-PLUGINS\-CHECK\-POLICY" "1" "March 2023" "" ""
.
.SH "NAME"
\fBpodsec\-nagios\-plugins\-check\-policy\fR \- Плугин проверяет политики настройки контейнеризации на сервере
.
.SH "SYNOPSIS"
\fBpodsec\-nagios\-plugins\-check\-policy\fR
.
.SH "DESCRIPTION"
Плугин проверяет политики настройки контейнеризации на сервере
.
.SH "OPTIONS"
.
.SH "EXAMPLES"
`podsec\-nagios\-plugins\-check\-policy
.
.SH "SECURITY CONSIDERATIONS"
.
.SH "SEE ALSO"
.
.SH "AUTHOR"
Костарев Алексей, Базальт СПО kaf@basealt\.ru
