.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PODSEC\-NAGIOS\-PLUGINS\-CHECK\-POLICY" "1" "March 2023" "" ""
.
.SH "NAME"
\fBpodsec\-nagios\-plugins\-check\-policy\fR \- Плугин проверяет политики настройки контейнеризации на узле
.
.SH "SYNOPSIS"
\fBpodsec\-nagios\-plugins\-check\-policy [\-v[vv]] [\-a интервал] [\-f интервал] \-c интервал \-h интервал [\-m интервал] \-w интервал [\-l интервал] [\-d интервал]\fR
.
.SH "DESCRIPTION"
.
.SS "Общее описание"
Плугин проверяет политики настройки контейнеризации на узле\.
.
.P
Проверка идет по следующим параметрам:
.
.TP
файл \fBpolicy\.json\fR установки транспортов и политик доступа к регистраторам:

.
.IP "" 4
.
.nf


    Параметр контроля                                                                                                         | Вес метрики
    \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-|\-\-\-\-\-\-\-\-\-\-\-\-\-
    имеющих `defaultPolicy != reject`, но не входящих в группу `podman_dev`                                                   | 102
    не имеющих не имеющих `registry\.local` в списке регистраторов для которых проверяется наличие электронной подписи образов | 103
    имеющих в политике регистраторы для которых не проверяется наличие электронной подписи образов                            | 104
    имеющих в списке поддерживаемых транспорты отличные от `docker` (транспорт получения образов с регистратора)              | 105
.
.fi
.
.IP "" 0
.
.TP
файлы привязки регистраторов к серверам хранящим электронные подписи (файл привязки о умолчанию \fBdefault\.yaml\fR и файлы привязки регистраторов \fB*\.yaml\fR каталога \fBregistries\.d\fR)\. Наличие (число) пользователей:

.
.IP "" 4
.
.nf


    Параметр контроля                                                                                            | Вес метрики
    \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-|\-\-\-\-\-\-\-\-\-\-\-\-\-
    не использующих хранилище подписей  `http://sigstore\.local:81/sigstore/` как хранилище подписей по умолчанию | 106
.
.fi
.
.IP "" 0
.
.IP "\[ci]" 4
контроль групп пользователей
.
.TP
наличие пользователей имеющих образы, но не входящих в группу \fBpodman\fR:


.
.IP "" 0
.
.IP "" 4
.
.nf


        Параметр контроля                                                      | Вес метрики
        \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-|\-\-\-\-\-\-\-\-\-\-\-\-\-
        наличие пользователей имеющих образы, но не входящих в группу `podman` | 101
.
.fi
.
.IP "" 0
.
.IP "" 4
.
.nf

* наличие пользователей группы `podman` (за исключением входящих в группу `podman_dev`):
.
.fi
.
.IP "" 0
.
.IP "" 4
.
.nf


        Параметр контроля | Вес метрики
        \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-|\-\-\-\-\-\-\-\-\-\-\-\-\-
        входящих в группу `wheel`                                            | 107
        имеющих каталог `\.config/containers/` открытым на запись и изменения | 90 * `доля_нарушителей`
        не имеющих файла конфигурации `\.config/containers/storage\.conf`      | 90 * `доля_нарушителей
.
.fi
.
.IP "" 0
.
.P
\fBдоля_нарушителей\fR считается как: \fBчисло_нарушителей / число_пользователей_группы_podman\fR
.
.P
Все веса метрик суммируются и формируется итоговая метрика\.
.
.SH "OPTIONS"
Уровень опасности определяется при запуске флагами:
.
.TP
для системных логов:

.
.IP "" 4
.
.nf


    Имя уровня  | Уровень | Префикс    | Флаг | Рекомендуемое значение интервала
    \-\-\-\-\-\-\-\-\-\-\-\-|\-\-\-\-\-\-\-\-\-|\-\-\-\-\-\-\-\-\-\-\-\-|\-\-\-\-\-\-|\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
    аварийный   |    7    | Crash      | `\-a` | не указывать
    фатальный   |    6    | Fatal      | `\-f` | не указывать
    критический |    5    | Critical   | `\-c` | 100
    высокий     |    4    | Heigh      | `\-h` | 0
    средний     |    3    | Middle     | `\-m` | не указывать
    низкий      |    2    | Low        | `\-l` | не указывать
    отладочный  |    1    | Debug      | `\-d` | не указывать
.
.fi
.
.IP "" 0
.
.TP
для сервера \fBnagios\fR:

.
.IP "" 4
.
.nf


    Имя уровня     | Уровень | Префикс    | Флаг | Рекомендуемое значение интервала
    \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-|\-\-\-\-\-\-\-\-\-|\-\-\-\-\-\-\-\-\-\-\-\-|\-\-\-\-\-\-|\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
    критический    |    2    | Critical   | `\-c` | 100
    предупреждение |    1    | Warning    | `\-w` | 0
.
.fi
.
.IP "" 0
.
.P
Любой параметр может отсутствовать\. В этом случае он не рассматривается при просмотре соответствия полученной метрики интервалам\.
.
.P
Значение параметров имеют формат интервала, описанного в документации по nagios: Threshold and Ranges \fIhttps://nagios\-plugins\.org/doc/guidelines\.html#THRESHOLDFORMAT\fR\.
.
.P
Общее описание:
.
.P
\fB[@]start:end\fR
.
.P
Замечание:
.
.IP "\[ci]" 4
\fBstart\fR ≤ \fBend\fR
.
.IP "\[ci]" 4
\fBstart\fR и \fB:\fR не требуется если \fBstart=0\fR
.
.IP "\[ci]" 4
если интервал задан в формате \fBstart:\fR и конец не задан, то концом интервала считается бесконечность \fBꝏ\fR
.
.IP "\[ci]" 4
для указания отрицательной бесконечности (\fB\-ꝏ\fR) используйте \fB~\fR
.
.IP "\[ci]" 4
триггер срабатывает когда значение метрики \fBВНЕ УКАЗАННОГО ИНТЕРВАЛА\fR (\fBначальные и конечные точки включаются в интервал\fR)
.
.IP "\[ci]" 4
если интервал начинается с символа \fB@\fR, тогда условие инвертируется \- триггер срабатывает при значении метрики \fBВ УКАЗАННОМ ИНТЕРВАЛЕ\fR (начальные и конечные точки включаются в интервал)
.
.IP "" 0
.
.P
Примеры возможных форматов:
.
.IP "" 4
.
.nf


Формат интервала | Описание условия срабатывания триггера
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-|\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
100              | metrica < 0 || metrica > 100 (вне интервала 0\-100)
100:             | metrica < 100 (вне интервала 100\-ꝏ)
~:100            | metrica > 100 (вне интервала \-ꝏ\-100)
20\-100           | metrica < 20 || metrica > 100 (вне интервала 20\-100)
@20\-100          | metrica >= 20 && metrica <= 100 (в интервале 20\-100)
.
.fi
.
.IP "" 0
.
.SS "Системные логи"
Для системных логов уровень опасности определяется для каждого сообщения\. Интервалы уровней опасностей, заданные параметрами просматриваются в порядке от большого к меньшему\. Уровень сообщения определяется по первому найденному соответствию (не забываете, что триггер срабатывает при нахождении метрики ВНЕ интервала)\. Если соответствие не найдено, сообщение в системный лог не выводится\.
.
.P
Исходя найденного уровня определяет приоритет сообщения и его тег (префикс)\. В системный лог командой logger посылается сообщение с указанным приоритетом и тегом:
.
.IP "" 4
.
.nf


# logger \-p приоритет \-t тег "тег: сообщение"
.
.fi
.
.IP "" 0
.
.P
Кроме основного сообщения для \fBnagios\fR формируются:
.
.IP "\[ci]" 4
список пользователей нарушителей;
.
.IP "\[ci]" 4
укороченные сообщения для уровня детализации \fB1\fR\.
.
.IP "" 0
.
.SS "Логи nagios"
Форматы сообщений и кодов завершения плугина описаны в Plugin Output for Nagios \fIhttps://nagios\-plugins\.org/doc/guidelines\.html#PLUGOUTPUT\fR\.
.
.P
Уровень опасности для логов nagios определяется СУММАРНОЙ метрике\. Суммарная метрика определяется для определения уровня сравнивается с интервалами, задаваемыми флагами
.
.IP "\[ci]" 4
\fB\-c\fR \- \fBCritical\fR
.
.IP "\[ci]" 4
\fB\-w\fR \- \fBWarning\fR
.
.IP "" 0
.
.P
Если соответствие не найдено, в \fBnagios\fR выводится сообщение:
.
.IP "" 4
.
.nf


POLICY OK: Политики контейнеризации не нарушены
.
.fi
.
.IP "" 0
.
.P
Код завершение программы (которое обрабатывается на стороне сервера \fBnagios\fR) \- \fB0\fR\.
.
.P
Формат логов для \fBnagios\fR зависит от уровня детализации, задаваемый флагом \fB\-v[vv]\fR (см\. Verbose Output \fIhttps://nagios\-plugins\.org/doc/guidelines\.html#AEN41\fR):
.
.IP "" 4
.
.nf


Флаг        | Уровень
\-\-\-\-\-\-\-\-\-\-\-\-|\-\-\-\-\-\-\-\-
отcутствует | 0
\-v          | 1
\-vv         | 2
\-vvv        | 3
\|\.\|\.\|\.         | 3
.
.fi
.
.IP "" 0
.
.P
Для всех уровней формируется префикс сообщение формата:
.
.IP "" 4
.
.nf


POLICY $prefix:
.
.fi
.
.IP "" 0
.
.P
Где \fBprefix\fR в зависимости от уровня опасности принимает значения:
.
.IP "\[ci]" 4
\fB\-c\fR \- \fBCritical\fR
.
.IP "\[ci]" 4
\fB\-w\fR \- \fBWarning\fR
.
.IP "" 0
.
.P
Если уровень детализации \- \fB0\fR, то выводится укороченное сообщение\.
.
.IP "" 4
.
.nf


POLICY $prefix: Нарушение политик контейнеризации пользователей \fIusers\fR
.
.fi
.
.IP "" 0
.
.P
Где \fBusers\fR \- список пользователей у которых обнаружены нарушения\.
.
.P
Если уровень детализации \- \fB1\fR, то к сообщению с префиксом \fIЕсть пользователи:\fR добавляется первый уровень детализации из списка укороченных сообщений сформированных при формировании системных логов\.
.
.IP "" 4
.
.nf


POLICY $prefix: Нарушение политик контейнеризации пользователей $users | Есть пользователи:
укороченное сообщение
\|\.\|\.\|\.
.
.fi
.
.IP "" 0
.
.P
Если уровень детализации \- \fB2\fR, то к сообщению добавляется второй уровень детализации из списка полных сообщений сформированных при формировании системных логов\.
.
.IP "" 4
.
.nf


POLICY $prefix: Нарушение политик контейнеризации пользователей $users | Есть пользователи:
укороченное сообщение
\|\.\|\.\|\.
укороченное сообщение |
полное сообщение
\|\.\|\.\|\.
.
.fi
.
.IP "" 0
.
.P
После вывода сообщений плугин завершается кодом завершения:
.
.IP "\[ci]" 4
\fBCritical\fR \- \fB2\fR
.
.IP "\[ci]" 4
\fBWarning\fR \- \fB1\fR
.
.IP "" 0
.
.SH "EXAMPLES"
Проанализировать политики политики с максимальным уровнем детализации\. Критический уровень (\fBnagios\fR, \fBsystem\fR) \fB>100\fR\. Уровень предупреждений (\fBnagios\fR) \fB>0\fR\. Низкий уровень (\fBsystem\fR) \fB>0\fR\.
.
.IP "" 4
.
.nf


# podsec\-nagios\-plugins\-check\-policy \-vvv  \-w 0 \-h 0 \-c 100
POLICY Critical(18): Нарушение политик контейнеризации пользователей  "imagedeveloper" "k8s\-user1" "kaf" "kafpodman" "podmanuser" "root" "securityadmin" "user" "user1"  | Есть пользователи:
вне группы podman,
способные получать любой образ
способные получать локальный образ без подписи
способные получать любой образ без подписи
способные получать любой образ через запрещенный транспорт
не использующие локальный хранитель подписей
входящие в группу wheel
не имеющих конфигурационного файла
способные изменить конфигурацию" |
Critical(101): Пользователи "kafpodman"  имеют образы, но не входят в группу \'podman\'
Critical(102): Пользователи "user"  имеют в policy\.json defaultPolicy!=reject, но не входят в группу \'podman_dev\'
Critical(103): Пользователи "user"  не имеют registry\.local в списке регистраторов для которых проверяется наличие электронной подписи образов
Critical(104): Пользователи "root" "kaf" "kafpodman" "podmanuser" "securityadmin" "user1"  имеют в политике регистраторы для которых не проверяется наличие электронной подписи образов
Critical(105): Пользователи "user"  имеют в списке поддерживаемых транспорты отличные от docker
Critical(106): Пользователи "imagedeveloper" "user"  не используют хранилище подписей  http://sigstore\.local:81/sigstore/ как хранилище подписей по умолчанию
Critical(107): Пользователи  "kaf" "securityadmin" входят в группы \'podman\' и \'wheel\'
High(72): Пользователи  "k8s\-user1" "kaf" "securityadmin" "user1" не имеют конфигурационного файла \.config/containers/storage\.conf
High(18): Пользователи  "user" имеют открытым для записи каталог конфигурации \.config/containers

.
.fi
.
.IP "" 0
.
.SH "SECURITY CONSIDERATIONS"
.
.SH "SEE ALSO"
.
.IP "\[ci]" 4
Nagios Plugins\. Development Guidelines \fIhttps://nagios\-plugins\.org/doc/guidelines\.html#PLUGOUTPUT\fR
.
.IP "" 0
.
.SH "AUTHOR"
Костарев Алексей, Базальт СПО kaf@basealt\.ru
