.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "PODSEC\-CREATE\-POLICY" "1" "October 2024" ""
.SH "NAME"
\fBpodsec\-create\-policy\fR \- creating system policies and configuration files
.SH "SYNOPSIS"
\fBpodsec\-create\-policy ip\-address_of_registrar_and_signature_server\fR
.SH "DESCRIPTION"
The script creates policy files and configures system services for \fBpodman\fR to work in both \fBrootfull\fR and \fBrootless\fR modes:
.IP "\[ci]" 4
Adds to the \fB/etc/hosts\fR file a binding of the \fBregistry\.local\fR, \fBsigstore\.local\fR domains to the specified \fBip\-address_of_registrar_and_signature_server\fR;
.IP "\[ci]" 4
Creates, preserving the previous policy file \fB/etc/containers/policy\.json\fR;
.IP "\[ci]" 4
Creates and preserves the previous file \fB/etc/containers/registries\.d/default\.yaml\fR describing access to signatories\' public keys;
.IP "\[ci]" 4
Creates the group \fBpodman\fR;
.IP "\[ci]" 4
If the \fBip\-address_of_the_registrar_and_signature_server\fR matches the local IP\-address, creates the group \fBpodmen_dev\fR and initializes the directory \fB/var/sigstore/\fR and subdirectories for storing public keys and image signatures;
.IP "\[ci]" 4
Adds insecure access to the registrar \fBregistry\.local\fR to the file \fB/etc/containers/registries\.conf\fR;
.IP "\[ci]" 4
Configures the use of the image \fBregistry\.local/k8s\-c10f1/pause:3\.9\fR when starting \fBpod\fRs in \fBpodman\fR (\fBpodman pod init\fR);
.IP "" 0
.SH "SECURITY CONSIDERATIONS"
.IP "\[ci]" 4
The IP address of the registrar and signature server must not be local \fB127\.0\.0\.1\fR
.IP "\[ci]" 4
If the binding of the domains \fBregistry\.local\fR, \fBsigstore\.local\fR in the file \fB/etc/hosts\fR already exists, the script terminates with the exit code \fB1\fR\. It is necessary to remove the binding line and restart the script\.
.IP "\[ci]" 4
If the script is run on a cluster node other than \fBsigstore\.local\fR, then after the script has run, it is necessary to copy the policy file \fB/etc/containets/policy\.json\fR from the node \fBsigstore\.local\fR to the corresponding directory \fB/etc/containets/\fR\. This operation must be performed each time a user signing images on \fBsigstore\.local\fR is added\.
.IP "" 0
.SH "SEE ALSO"
.IP "\[ci]" 4
Description of periodic integrity monitoring of container images and containerization tool settings \fIhttps://github\.com/alt\-cloud/podsec/tree/master/ImageSignatureVerification\fR
.IP "" 0
.SH "AUTHOR"
Aleksey Kostarev, Basealt SPO kaf@basealt\.ru
