.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "PODSEC\-INOTIFY\-CHECK\-KUBEAPI" "1" "October 2024" ""
.SH "NAME"
\fBpodsec\-inotify\-check\-kubeapi\fR \- скрипт мониторинга аудита API\-интерфейса kube\-apiserver control\-plane узла
.SH "SYNOPSIS"
\fBpodsec\-inotify\-check\-kubeapi [\-d]\fR
.SH "DESCRIPTION"
Скрипт производит мониторинг файла \fB/etc/kubernetes/audit/audit\.log\fR аудита API\-интерфейса \fBkube\-apiserver\fR\.
.P
Политика аудита располагается в файле \fB/etc/kubernetes/audit/policy\.yaml\fR:
.IP "" 4
.nf
apiVersion: audit\.k8s\.io/v1
kind: Policy
omitManagedFields: true
rules:
# do not log requests to the following
\- level: None
  nonResourceURLs:
  \- "/healthz*"
  \- "/logs"
  \- "/metrics"
  \- "/swagger*"
  \- "/version"
  \- "/readyz"
  \- "/livez"

\- level: None
  users:
    \- system:kube\-scheduler
    \- system:kube\-proxy
    \- system:apiserver
    \- system:kube\-controller\-manager
    \- system:serviceaccount:gatekeeper\-system:gatekeeper\-admin

\- level: None
  userGroups:
    \- system:nodes
    \- system:serviceaccounts
    \- system:masters

# limit level to Metadata so token is not included in the spec/status
\- level: Metadata
  omitStages:
  \- RequestReceived
  resources:
  \- group: authentication\.k8s\.io
    resources:
    \- tokenreviews

# extended audit of auth delegation
\- level: RequestResponse
  omitStages:
  \- RequestReceived
  resources:
  \- group: authorization\.k8s\.io
    resources:
    \- subjectaccessreviews

# log changes to pods at RequestResponse level
\- level: RequestResponse
  omitStages:
  \- RequestReceived
  resources:
  \- group: "" # core API group; add third\-party API services and your API services if needed
    resources: ["pods"]
    verbs: ["create", "patch", "update", "delete"]

# log everything else at Metadata level
\- level: Metadata
  omitStages:
  \- RequestReceived
.fi
.IP "" 0
.P
Текущие настройки производят логирование всех обращений "несистемных" пользователей (в том числе анонимных) к ресурсам \fBkubernetes\fR\.
.P
Скрипт производит выборку всех обращений, в ответ на которые был сформирован код более \fB400\fR \- запрет доступа\. Все эти факты записываются в системный журнал и накапливаются в файле логов \fB/var/lib/podsec/u7s/log/kubeapi/forbidden\.log\fR, который периодически передается через посту системному адмиристратору\.
.SH "OPTIONS"
.IP "\[ci]" 4
\fB\-d\fR \- скирпт запускается в режиме демона, производящего онлайн мониторинг файла \fB/etc/kubernetes/audit/audit\.log\fR и записывающего факты запросов с запретом доступа в системный журнал и файл логов \fB/var/lib/podsec/u7s/log/kubeapi/forbidden\.log\fR\.
.IP "\[ci]" 4
\fB\-m\fR \- скрипт посылает файл логов \fB/var/lib/podsec/u7s/log/kubeapi/forbidden\.log\fR почтой системному администратору (пользователь \fBroot\fR) и обнуляет файл логов\.
.IP "" 0
.P
В состав пакета кроме этого скрипта входят:
.IP "\[ci]" 4
файл описания сервиса \fB/lib/systemd/system/podsec\-inotify\-check\-kubeapi\.service\fR\. Для его запуска необходимо выполнить команды:
.IP "\[ci]" 4
Файла расписания \fB/lib/systemd/system/podsec\-inotify\-check\-kubeapi\-mail\.timer\fR, задающий в параметре \fBOnCalendar\fR расписание запуска сервиса \fB/lib/systemd/system/podsec\-inotify\-check\-kubeapi\-mail\.timer\fR\. Таймер вызывается ежечасно\.
.IP "" 0
.P
По умолчанию таймер запуска сервиса выключен\. Для его включения наберите команду:
.IP "" 4
.nf
#  systemctl enable \-\-now podsec\-inotify\-check\-kubeapi\-mail\.timer
.fi
.IP "" 0
.P
Если необходимо изменить режим запуска скрипта отредактируйте параметр \fBOnCalendar\fR файла расписания \fBpodsec\-inotify\-check\-kubeapi\-mail\.timer\fR\.
.SH "EXAMPLE"
\fBpodsec\-inotify\-check\-kubeapi \-d\fR
.P
\fBpodsec\-inotify\-check\-kubeapi \-m\fR
.SH "SECURITY CONSIDERATIONS"
Кроме мониторинга фактов запрета доступа возможен мониторинг других фактов подозрительной активности\.
.SH "SEE ALSO"
.IP "\[ci]" 4
Auditing \fIhttps://kubernetes\.io/docs/tasks/debug/debug\-cluster/audit/\fR
.IP "\[ci]" 4
kube\-apiserver Audit Configuration (v1) \fIhttps://kubernetes\.io/docs/reference/config\-api/apiserver\-audit\.v1/\fR
.IP "\[ci]" 4
Kubernetes Audit Logs \- Best Practices And Configuration \fIhttps://signoz\.io/blog/kubernetes\-audit\-logs/\fR
.IP "\[ci]" 4
How to monitor Kubernetes audit logs \fIhttps://www\.datadoghq\.com/blog/monitor\-kubernetes\-audit\-logs/#monitor\-api\-authentication\-issues\fR
.IP "" 0
.SH "AUTHOR"
Костарев Алексей, Базальт СПО kaf@basealt\.ru
